# Generated by Django 4.1.7 on 2023-03-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('DDN', models.DateField(default='1900-10-10', verbose_name='Date de Naissance')),
                ('DDD', models.DateField(blank=True, null=True, verbose_name='Date de Décès')),
                ('wiki_id', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['DDN'],
            },
        ),
        migrations.CreateModel(
            name='Cercle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, null=True)),
                ('ami_name', models.CharField(max_length=250, null=True, verbose_name='Rechercher un ami :')),
                ('user_id', models.IntegerField()),
                ('ami_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidat_wiki_id', models.CharField(max_length=20, null=True)),
                ('user_id', models.IntegerField()),
                ('candidat_nom', models.CharField(max_length=250, null=True)),
                ('username', models.CharField(max_length=250, null=True)),
                ('mort', models.BooleanField(default=False)),
            ],
        ),
    ]
