# Generated by Django 4.1.7 on 2023-05-15 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JeuDeLaMort', '0002_alter_cercle_ami_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20, null=True)),
                ('candidats_uniques', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='candidat',
            name='wiki_id',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Pari_unique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidat_wiki_id', models.CharField(max_length=20, null=True)),
                ('user_id', models.IntegerField()),
                ('mort', models.BooleanField(default=False)),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JeuDeLaMort.ligue')),
            ],
        ),
        migrations.CreateModel(
            name='Ligue_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JeuDeLaMort.ligue')),
            ],
        ),
    ]
