# Generated by Django 4.1.7 on 2023-05-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JeuDeLaMort', '0004_rename_candidat_wiki_id_pari_unique_wiki_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligue',
            name='lancee',
            field=models.BooleanField(default=False),
        ),
    ]
