# Generated by Django 4.1.7 on 2023-05-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JeuDeLaMort', '0005_ligue_lancee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligue',
            name='identifiant',
            field=models.IntegerField(null=True),
        ),
    ]
