# Generated by Django 4.1.7 on 2023-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JeuDeLaMort', '0006_ligue_identifiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligue',
            name='identifiant',
        ),
        migrations.AddField(
            model_name='ligue_user',
            name='identifiant',
            field=models.IntegerField(null=True),
        ),
    ]
