# Generated by Django 4.1.7 on 2023-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JeuDeLaMort', '0007_remove_ligue_identifiant_ligue_user_identifiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligue_user',
            name='identifiant',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
    ]
