# Generated by Django 4.1.7 on 2023-05-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JeuDeLaMort', '0008_alter_ligue_user_identifiant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pari',
            old_name='candidat_wiki_id',
            new_name='wiki_id',
        ),
    ]
