# Generated by Django 4.1.7 on 2023-05-19 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JeuDeLaMort', '0009_rename_candidat_wiki_id_pari_wiki_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligue',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligue',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Ce cercle est public'),
        ),
    ]
