# Generated by Django 4.1.7 on 2023-08-11 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JeuDeLaMort', '0010_ligue_createur_ligue_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='pari',
            name='candidat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JeuDeLaMort.candidat'),
        ),
        migrations.AddField(
            model_name='pari',
            name='joueur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
