# Generated by Django 4.1.7 on 2023-08-11 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JeuDeLaMort', '0011_pari_candidat_pari_joueur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligue_user',
            name='ligue',
        ),
        migrations.RemoveField(
            model_name='pari_unique',
            name='ligue',
        ),
        migrations.RemoveField(
            model_name='cercle',
            name='ami_id',
        ),
        migrations.RemoveField(
            model_name='cercle',
            name='ami_name',
        ),
        migrations.RemoveField(
            model_name='cercle',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='cercle',
            name='username',
        ),
        migrations.RemoveField(
            model_name='pari',
            name='candidat_nom',
        ),
        migrations.RemoveField(
            model_name='pari',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='pari',
            name='username',
        ),
        migrations.RemoveField(
            model_name='pari',
            name='wiki_id',
        ),
        migrations.AddField(
            model_name='cercle',
            name='ami',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ami', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cercle',
            name='joueur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joueur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Ligue',
        ),
        migrations.DeleteModel(
            name='Ligue_user',
        ),
        migrations.DeleteModel(
            name='Pari_unique',
        ),
    ]
