# Generated by Django 4.1.7 on 2023-08-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JeuDeLaMort', '0012_remove_ligue_user_ligue_remove_pari_unique_ligue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cercle',
            name='ami_name',
            field=models.CharField(max_length=250, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cercle',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pari',
            name='candidat_nom',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pari',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pari',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pari',
            name='wiki_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
