# Generated by Django 4.1.7 on 2023-12-15 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JeuDeLaMort', '0015_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='pari',
            name='passe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pari',
            name='saison',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='preference',
            name='infos',
            field=models.BooleanField(default=True, verbose_name='Rester informé.e des évolutions du Jeu de la Mort'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='newsletter',
            field=models.BooleanField(default=True, verbose_name="Etre prévenu.e lorsqu'un candidat rapporte des points"),
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.IntegerField(default=2023)),
                ('score', models.IntegerField(default=0)),
                ('joueur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
