# Generated by Django 4.1.7 on 2024-05-16 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JeuDeLaMort', '0016_pari_passe_pari_saison_alter_preference_infos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.FileField(storage=True, upload_to='static/prouts', verbose_name='Enregistrement')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
