# Generated by Django 4.1.7 on 2024-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JeuDeLaMort', '0017_prout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prout',
            name='performance',
            field=models.FileField(upload_to='static/prouts'),
        ),
    ]
